[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  HUGO_VERSION = "0.29"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.29"
  command = "npm run build-preview"
